import type { Metadata } from "next";

/**
 * Single source of truth for business details used in metadata, the
 * sitemap and structured data. Set NEXT_PUBLIC_SITE_URL per environment.
 */
export const site = {
  name: "Sigma Business Finance",
  legalName: "Sigma Business Finance Ltd",
  url: (process.env.NEXT_PUBLIC_SITE_URL ?? "https://sigmabusinessfinance.co.uk").replace(/\/$/, ""),
  description:
    "Sigma Business Finance connects UK businesses with 50+ specialist lenders. Business loans, invoice finance, asset finance and more — decisions in 24–48 hours, no upfront fees.",
  phone: "+44 151 837 3528",
  email: "contact@sigmabusinessfinance.co.uk",
  companyNumber: "15732726",
  address: {
    streetAddress: "Commerce Park, Campbeltown Road",
    addressLocality: "Birkenhead",
    postalCode: "CH41 9HP",
    addressCountry: "GB",
  },
};

// Generated by src/app/opengraph-image.tsx. Pages that set their own openGraph
// object lose the file-based image, so pageMetadata re-attaches it explicitly.
const shareImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Sigma Business Finance — fast, flexible UK business funding",
};

export const absoluteUrl = (path = "/") => `${site.url}${path === "/" ? "" : path}`;

type PageMetadataInput = {
  title: string;
  description: string;
  path: string;
  noIndex?: boolean;
};

/**
 * Builds page metadata with a canonical URL and matching Open Graph /
 * Twitter tags. Next shallow-merges metadata between segments, so each
 * page must supply its own openGraph object rather than inherit the root's.
 */
export function pageMetadata({ title, description, path, noIndex }: PageMetadataInput): Metadata {
  // Open Graph titles don't use the root title template, so add the brand here.
  const socialTitle = title.includes(site.name) ? title : `${title} | ${site.name}`;

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "en_GB",
      siteName: site.name,
      title: socialTitle,
      description,
      url: path,
      images: [shareImage],
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images: [shareImage],
    },
    ...(noIndex ? { robots: { index: false, follow: true } } : {}),
  };
}

type Faq = { question: string; answer: string };

export const faqJsonLd = (faqs: Faq[]) => ({
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: { "@type": "Answer", text: faq.answer },
  })),
});

export const breadcrumbJsonLd = (items: { name: string; path: string }[]) => ({
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: items.map((item, i) => ({
    "@type": "ListItem",
    position: i + 1,
    name: item.name,
    item: absoluteUrl(item.path),
  })),
});

export const serviceJsonLd = ({
  name,
  description,
  path,
}: {
  name: string;
  description: string;
  path: string;
}) => ({
  "@context": "https://schema.org",
  "@type": "Service",
  name,
  description,
  url: absoluteUrl(path),
  serviceType: name,
  areaServed: { "@type": "Country", name: "United Kingdom" },
  provider: { "@id": `${site.url}/#organization` },
});

export const organizationJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "FinancialService",
      "@id": `${site.url}/#organization`,
      name: site.name,
      legalName: site.legalName,
      url: site.url,
      logo: `${site.url}/icon.svg`,
      image: `${site.url}/opengraph-image`,
      description: site.description,
      telephone: site.phone,
      email: site.email,
      identifier: {
        "@type": "PropertyValue",
        propertyID: "Companies House",
        value: site.companyNumber,
      },
      address: { "@type": "PostalAddress", ...site.address },
      areaServed: { "@type": "Country", name: "United Kingdom" },
    },
    {
      "@type": "WebSite",
      "@id": `${site.url}/#website`,
      name: site.name,
      url: site.url,
      publisher: { "@id": `${site.url}/#organization` },
      inLanguage: "en-GB",
    },
  ],
};
